sudo: false
dist: trusty
language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - cmake
    - libpthread-stubs0-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libglew1.5-dev
    - libjpeg8-dev
    - libvorbis-dev
    - libsndfile1-dev
    - libopenal-dev
    - libflac-dev
cache:
      directories:
      - $HOME/SFML-2.5.0_LINUX
    script:
      - chmod +x tests/travis_linux_tests.sh
      - CXX=$COMPILER tests/travis_linux_tests.sh
after_success: bash <(curl -s https://codecov.io/bash) -x gcov-6 -a "-s /home/travis/build/texus/TGUI -pr"
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi

script:
  - mkdir build
  - cd build
  - gcc -v && g++ -v && cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh
  - chmod +x cmake-3.12.3-Linux-x86_64.sh
  - ./cmake-3.12.3-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

