sudo: true
dist: trusty
language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - gcc-7
    - cmake


before_script:
  -wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz -o /tmp/sfml.tar.gz
  -tar -xzvf /tmp/sfml.tar.gz
  -sudo cp -r SFML-2.4.2/* /usr/
  -sudo apt-get install -u libjprg62-dev libsndfile1-dev libglewl1.5 libglewl1.5-dev libfreetype6 libjpeg-turbo8v libjpeg8 libopenal-dev
before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh
  - chmod +x cmake-3.12.3-Linux-x86_64.sh
  - ./cmake-3.12.3-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi

script:
  - mkdir build
  - cd build
  - gcc -v && g++ -v && cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make



